<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>ADA_MKII_API</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ElevenLabs-DotNet" Version="1.3.5" />
    <PackageReference Include="OpenAI" Version="1.7.2" />
  </ItemGroup>

</Project>
